logging:
  level:
    com:
      ningze:
        risk: debug
    org:
      hibernate: error

spring:
  datasource:
    url: jdbc:mysql://47.94.241.154:3306/nikekun?useUnicode=yes&characterEncoding=UTF8
    username: root
    password: 1234
    driver-class-name: com.mysql.jdbc.Driver
    hikari:
      max-lifetime: 1765000
      maximum-pool-size: 15
  jpa:
    showSql: true
  redis:
    ##redis位置放在了啊腾讯云
    host: 49.234.6.120
    port: 6379
    password: cp520822
    timeout: 10000
    jedis:
      pool:
        max-active: 300
        min-idle: 100
        max-idle: 100
        max-wait: 10000
  aop:
    proxy-target-class: true
    auto: true

eureka:
  client:
    enabled: false
