logging:
  level:
    com:
      ningze:
        ming: debug
    org:
      hibernate: error

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/nikekun?useUnicode=yes&characterEncoding=UTF8
    username: root
    password: 1234
    driver-class-name: com.mysql.cj.jdbc.Driver
    

    
    hikari:
      max-lifetime: 1765000
      maximum-pool-size: 15
  jpa:
      showSql: true
#      properties: 
#        hibernate: 
#          dialect: org.hibernate.dialect.Oracle10gDialect

  aop:
    proxy-target-class: true
    auto: true

eureka:
  client:
    enabled: false
