logging:
  level:
    com:
      ningze:
        risk: debug


spring:
  datasource:
    url: jdbc:mysql://localhost:3306/bbq?useUnicode=yes&characterEncoding=UTF8
    username: root
    password: 123456
    driver-class-name: com.mysql.jdbc.Driver
    hikari:
      max-lifetime: 1765000
      maximum-pool-size: 15
  jpa:
      showSql: true
  redis:
    host: localhost
    port: 6379
#    password: 123456
    timeout: 10000
    jedis:
      pool:
        max-active: 10
        min-idle: 3
        max-idle: 5
  aop:
    proxy-target-class: true
    auto: true


eureka:
  client:
    enabled: false
