logging:
  level:
    com:
      ningze:
        risk: debug

spring:
  datasource:
    url: jdbc:mysql://172.16.8.18:3306/nzrisk-poc?useUnicode=yes&characterEncoding=UTF8
    username: nzdev
    password: Nzjrkj_DEV
    driver-class-name: com.mysql.jdbc.Driver
    hikari:
      max-lifetime: 1765000
      maximum-pool-size: 15
  jpa:
      showSql: true
  redis:
    host: 172.16.8.29
    port: 6379
    password: nzjrkj
    timeout: 10000
    jedis:
      pool:
        max-active: 300
        min-idle: 100
        max-idle: 100
        max-wait: 10000
  aop:
    proxy-target-class: true
    auto: true



eureka:
  client:
    enabled: false
